---
title: "Reflection exercise 4"
date: today
date-format: long
format: pdf
number_sections: true
toc: true
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(janitor)
library(knitr)
```



```{r}
#| include: false
#| warning: false
#| message: false

acs_2022 <- read_csv("../data/raw/usa_00001 3.csv") %>% clean_names()
head(acs_2022)

```

# Question 1

## How many respondents were there in each state (stateicp) that had a doctoral degree as their highest educational attainment (EDUC)?

```{r}
#| echo: false
#| warning: false
#| message: false
#| tbl-cap: "Number of Respondents and Proportion of Doctors Per State"

# table, stateicp, number of doctors

doctor_prop_table <- acs_2022 %>% 
  select(stateicp, educd) %>% filter(!is.na(stateicp) & !is.na(educd)) %>% 
  group_by(stateicp) %>% 
  summarise(number_of_respondents = n(), 
            number_of_doctors = sum(educd == 116),
            doctor_proportion = number_of_doctors / number_of_respondents)


doctor_prop_table %>% kable(col.names = 
                              c("State ICP", 
                                "Respondent Count", 
                                "Doctor Count", "Doctor Proportion"))

```

## Laplace to estimator. Given 391,171 California Respondents use estimator to find number of participants for all states.

```{r}
#| echo: false
#| warning: false
#| message: false
#| tbl-cap: "Esimated Number of Respondents Per State"

# california is 71# 391,171 from table and from the quercus directions

# reducing data for estimator question purposes
cali_resp_count <- 391171
state_doctors_count <- doctor_prop_table %>% select(stateicp, number_of_doctors)

california_doctor_prop <- as.numeric((state_doctors_count %>% filter(stateicp == 71) %>% 
  select(number_of_doctors)) / cali_resp_count)

number_of_respondents_estimate <- state_doctors_count %>% mutate(
  estimate_respondent_count = round(number_of_doctors / california_doctor_prop)
)

number_of_respondents_estimate %>% kable(col.names = 
                                           c("State ICP", "Doctor Count", 
                                             "Estimated Respondent Count"))


```

### Different between estimator and non estimator


```{r}
#| echo: false
#| warning: false
#| message: false
#| label: diff
#| tbl-cap: "Esimated Number of Respondents Per State"
number_of_respondents_estimate %>% 
  select(stateicp, estimate_respondent_count) %>%
  inner_join(doctor_prop_table, by = "stateicp") %>%
  select(stateicp, estimate_respondent_count, number_of_respondents) %>% 
  mutate(difference = estimate_respondent_count - number_of_respondents) %>% 
  kable(col.names = c("State ICP", "Estimated Respondent Count", 
                      "Respondent Count",
                      "Difference"))

```

Based on the @tbl-diff



